/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package controlpac;

import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author Administrador
 */
public class IngresoPacientesW extends javax.swing.JFrame {

    /**
     * Creates new form IngresoPacientesW
     */
    public IngresoPacientesW() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoCM.png")).getImage()); //Agrego el icono a la ventana
        
        setSize(450,400); //tamaño de ventana
        setLocationRelativeTo(null); //que se mueste en el centro
        setResizable(false);         
        setTitle("Ingreso de Datos"); // Le da un titulo a la ventana.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        datosPacienteBtn = new javax.swing.JButton();
        situacionPacBtn = new javax.swing.JButton();
        datosMedBtn = new javax.swing.JButton();
        ant = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mINI = new javax.swing.JMenuItem();
        mInf = new javax.swing.JMenuItem();
        opciones = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();
        cerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INGRESO DE DATOS");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 24, 424, 26);

        datosPacienteBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        datosPacienteBtn.setText("Datos del paciente");
        datosPacienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosPacienteBtnActionPerformed(evt);
            }
        });
        datosPacienteBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                datosPacienteBtnKeyTyped(evt);
            }
        });
        getContentPane().add(datosPacienteBtn);
        datosPacienteBtn.setBounds(100, 90, 220, 47);

        situacionPacBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        situacionPacBtn.setText("Situación del paciente");
        situacionPacBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                situacionPacBtnActionPerformed(evt);
            }
        });
        situacionPacBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                situacionPacBtnKeyTyped(evt);
            }
        });
        getContentPane().add(situacionPacBtn);
        situacionPacBtn.setBounds(100, 150, 220, 47);

        datosMedBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        datosMedBtn.setText("Datos del médico");
        datosMedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosMedBtnActionPerformed(evt);
            }
        });
        datosMedBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                datosMedBtnKeyTyped(evt);
            }
        });
        getContentPane().add(datosMedBtn);
        datosMedBtn.setBounds(100, 210, 220, 44);

        ant.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ant.setText("Anterior");
        ant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antActionPerformed(evt);
            }
        });
        ant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                antKeyTyped(evt);
            }
        });
        getContentPane().add(ant);
        ant.setBounds(38, 289, 94, 37);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 520, 360);

        jMenu2.setText("Ayuda");
        jMenu2.setToolTipText("");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Manual");
        jMenuItem2.setToolTipText("Vista de guía rápida de uso.");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ir a");

        mINI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mINI.setText("Menu Inicio");
        mINI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mINIActionPerformed(evt);
            }
        });
        jMenu3.add(mINI);

        mInf.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        mInf.setText("Informes");
        mInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mInfActionPerformed(evt);
            }
        });
        jMenu3.add(mInf);

        jMenuBar1.add(jMenu3);

        opciones.setText("Opciones");

        Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Salir.setText("Salir del Programa");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        opciones.add(Salir);

        cerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        cerrarSesion.setText("Cerrar Sesión");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        opciones.add(cerrarSesion);

        jMenuBar1.add(opciones);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datosPacienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosPacienteBtnActionPerformed
        // TODO add your handling code here:
        DatosPacienteW dp=new DatosPacienteW();
        dp.setVisible(true);
        dispose(); // se oculta la ventana de ingreso de datos.
    }//GEN-LAST:event_datosPacienteBtnActionPerformed

    private void situacionPacBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_situacionPacBtnActionPerformed
        // TODO add your handling code here:
        SituacionPacienteW sp=new SituacionPacienteW();
        sp.setVisible(true);
        dispose(); // se oculta la ventana de ingreso de datos.
    }//GEN-LAST:event_situacionPacBtnActionPerformed

    private void datosMedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosMedBtnActionPerformed
        // TODO add your handling code here:
        DatosMedicoW dm=new DatosMedicoW();
        dm.setVisible(true);
        dispose(); // se oculta la ventana de ingreso de datos.
    }//GEN-LAST:event_datosMedBtnActionPerformed

    private void antActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antActionPerformed
        // TODO add your handling code here:
        MainW menu=new MainW();
        menu.setVisible(true); // Vuelve el menu proncipal
        dispose(); // Desaparece el ingreso de datos.
  
    }//GEN-LAST:event_antActionPerformed

    private void antKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_antKeyTyped
        // TODO add your handling code here:
                // Creamos un evento para que cuando se presione la tecla Enter sea como presionar el botón.
        //******************************************************************************************
        char cTeclaPresionada=evt.getKeyChar();
        // da click al detectar la tecla ENTER.
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
            //Ejecuta el botón (dar click)
            ant.doClick();
        }// fin del if.
    }//GEN-LAST:event_antKeyTyped

    private void datosPacienteBtnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datosPacienteBtnKeyTyped
        // TODO add your handling code here:
                // Creamos un evento para que cuando se presione la tecla Enter sea como presionar el botón.
        //******************************************************************************************
        char cTeclaPresionada=evt.getKeyChar();
        // da click al detectar la tecla ENTER.
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
            //Ejecuta el botón (dar click)
            datosPacienteBtn.doClick();
        }// fin del if.
    }//GEN-LAST:event_datosPacienteBtnKeyTyped

    private void situacionPacBtnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_situacionPacBtnKeyTyped
        // TODO add your handling code here:
                // Creamos un evento para que cuando se presione la tecla Enter sea como presionar el botón.
        //******************************************************************************************
        char cTeclaPresionada=evt.getKeyChar();
        // da click al detectar la tecla ENTER.
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
            //Ejecuta el botón (dar click)
            situacionPacBtn.doClick();
        }// fin del if.
    }//GEN-LAST:event_situacionPacBtnKeyTyped

    private void datosMedBtnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datosMedBtnKeyTyped
        // TODO add your handling code here:
                // Creamos un evento para que cuando se presione la tecla Enter sea como presionar el botón.
        //******************************************************************************************
        char cTeclaPresionada=evt.getKeyChar();
        // da click al detectar la tecla ENTER.
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
            //Ejecuta el botón (dar click)
            datosMedBtn.doClick();
        }// fin del if.
    }//GEN-LAST:event_datosMedBtnKeyTyped

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        ManualW guiaRapida=new ManualW();
        guiaRapida.setVisible(true);
        setTitle("Manual de Ayuda");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mINIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mINIActionPerformed
        // TODO add your handling code here:
        MainW menu=new MainW();
        menu.setVisible(true); // Vuelve el menu proncipal
        dispose(); // Desaparece el informes.
    }//GEN-LAST:event_mINIActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0); // SE SALE DEL PROGRAMA.
    }//GEN-LAST:event_SalirActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        // TODO add your handling code here:
        Login log=new Login(); // Abre el log principal del sistema.
        log.setVisible(true); // Hace visible el log.
        dispose();//SE OCULTA
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void mInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mInfActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        InformesW iw=new InformesW();
        iw.setVisible(true); // Hago visible la ventana de Informes.
        dispose(); // Desaparece el menu.
    }//GEN-LAST:event_mInfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoPacientesW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoPacientesW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoPacientesW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoPacientesW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoPacientesW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Salir;
    private javax.swing.JButton ant;
    private javax.swing.JMenuItem cerrarSesion;
    private javax.swing.JButton datosMedBtn;
    private javax.swing.JButton datosPacienteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem mINI;
    private javax.swing.JMenuItem mInf;
    private javax.swing.JMenu opciones;
    private javax.swing.JButton situacionPacBtn;
    // End of variables declaration//GEN-END:variables
}
