/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package controlpac;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class Login extends javax.swing.JFrame {
    
        String usuarioValido="admin"; // Este es el usuario valido del sistema.
        String contraseñaValida="admin"; // Esta es la contraseña valida del sistema.
        String usuario=""; // Para el ingreso de usuario.
        String contraseña=""; // Para el ingreso de constraseña.
    /**
     * Creates new form Login
     */
    public Login() {
        
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoCM.png")).getImage()); //Agrego el icono a la ventana
        setSize(750,490);
        setLocationRelativeTo(null); // Para que el login aparezca en el centro de la pantalla.
        setResizable(false); // que no pueda agrandar la pantalla.
        setTitle("Identificación"); // Le da un titulo a la ventana.
        
    }
    
    public String getUsuario(){
        this.usuario=""; //La cadena Limpia.
        this.usuario=user.getText(); //Obtenemos el nombre de usuario ingresado.
        return usuario; // Devolvemos el nombre de usuario.
    }
    
    public String getPass(){
       this.contraseña=""; //Cadena de String vacía para luego guardar la contraseña ingresada.
       char [] pass=password.getPassword(); // Obtenemos la contraseña que ingresó el usuario.
       for(int i=0; i<pass.length;i++){ //Debemos realizar un for para copiar la pass ingresada a la cadena.
           this.contraseña+=pass[i]; //Se copia.
       }
        return contraseña;
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        ingresar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(getIconImages());
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acceso al Sistema", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Candara", 0, 12), java.awt.Color.darkGray)); // NOI18N

        jLabel1.setText("Usuario:");

        jLabel4.setText("Contraseña:");

        user.setToolTipText("Ingrese su nombre de usuario.");
        user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userKeyTyped(evt);
            }
        });

        password.setToolTipText("Ingrese su contraseña.");
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });

        ingresar.setText("Ingresar");
        ingresar.setToolTipText("Click para Ingresar al Sistema");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });
        ingresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresarKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ingresar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(password))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 150, 220, 120);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portadaL.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, -190, 820, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        // TODO add your handling code here:
        getUsuario(); //Obtenemos el usuario.
        getPass(); //Obtenemos la contraseña.
        // Se muestra un mensaje si alguno de los campos está vacío.
        if(this.usuario=="" || this.contraseña==""){
            JOptionPane.showMessageDialog(null, "Por favor, ingrese nombre de usuario y contraseña."); //Mensaje de Error.
        }else{        
            if(!this.usuario.equals(this.usuarioValido)){
                // Si el usuario y la contraseña no son válidos.
               if(!this.contraseña.equals(this.contraseñaValida))
                   JOptionPane.showMessageDialog(null,"Usuario y Contraseña no son válidos. Vuelva a ingresar.");
               else // Sólo el usuario no es válido.
                   JOptionPane.showMessageDialog(null, "El usuario no es correcto. Vuelva a ingresar.");
            }else{ // Sólo la contraseña no es válida.
                if(!this.contraseña.equals(this.contraseñaValida))
                   JOptionPane.showMessageDialog(null,"Contraseña Incorrecta. Vuelva a ingresar.");
                else{ //Contraseña y usuario son válidas.
                    MainW menu=new MainW();
                    menu.setVisible(true); // hace visibla la ventana de menu principal.
                    setTitle("Menú Principal"); // Le da un titulo a la ventana.
                    menu.setLocationRelativeTo(null);
                    dispose();
                }
            }                   
        }            
    }//GEN-LAST:event_ingresarActionPerformed

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
        // TODO add your handling code here:
        // Creamos un evento para que cuando se presione la tecla Enter sea como presionar INGRESAR.
        //El usuario puede ingresar la contraseña e ingresar con un Enter.
        //******************************************************************************************
        char cTeclaPresionada=evt.getKeyChar();
        // da click en el botón Ingresar al detectar la tecla ENTER.
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
            //Ejecuta el botón Ingresar (dar click)
            ingresar.doClick();
        }// fin del if.
              
    }//GEN-LAST:event_passwordKeyTyped

    private void userKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userKeyTyped
        // TODO add your handling code here:
        // Creamos un evento para que cuando se presione la tecla Enter sea como presionar INGRESAR.
        //El usuario puede ingresar el usuario e ingresar con un Enter.
        //******************************************************************************************
        char cTeclaPresionada=evt.getKeyChar();
        // da click en el botón Ingresar al detectar la tecla ENTER.
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
            //Ejecuta el botón Ingresar (dar click)
            ingresar.doClick();
        }// fin del if.
    }//GEN-LAST:event_userKeyTyped

    private void ingresarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresarKeyTyped
        // TODO add your handling code here:
        char cTeclaPresionada=evt.getKeyChar();
        // da click al detectar la tecla ENTER.
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
            //Ejecuta el botón (dar click)
            ingresar.doClick();
        }// fin del if.
    }//GEN-LAST:event_ingresarKeyTyped


    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true); //Hace visible el login.
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
